# Generated by Django 2.2.7 on 2020-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bustrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=10, null=True)),
                ('Destination', models.CharField(max_length=10, null=True)),
                ('Bus_Number', models.CharField(max_length=10, null=True)),
                ('Departure_Time', models.CharField(max_length=10, null=True)),
                ('Arrival_Time', models.CharField(max_length=10, null=True)),
                ('Distance', models.CharField(max_length=10, null=True)),
                ('Duration', models.CharField(max_length=10, null=True)),
                ('Number_of_Stops', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
